@Library('my-shared-library') _

pipeline {
  agent any

  parameters {
    choice(name:'actions', choices: 'create\ndelete', description: 'Choose Create or Destroy')
  }

  stages {
    // stage('SCM Checkout') {
    //   steps {
    //     script {
    //       gitCheckout(
    //         branch: "main",
    //         url: "https://github.com/mo7medsalah7/java-maven-k8s-jenkins"
    //       )
    //     }
    //   }
    // }


    // Maven Unit Test
    stage('Maven Unit Test') {
    when { expression { params.actions == "create" } }
      steps{
        script {
          mvnTest()
        }
      }
    }

      // Maven Integration Test
    stage('Maven Integration Test') {
    when { expression { params.actions == "create" } }
      steps{
        script {
          mvnIntegrationTest()
        }
      }
    }

    //  Static Code Analysis Maven
    stage('Maven Static Code Analysis') {
    when { expression { params.actions == "create" } }
      steps {
        script {
          staticCodeAnalysis()
        }
      }
    }
  }
}