@Library('my-shared-library') _

pipeline {
  agent any

  stages {
    stage('SCM Checkout') {
      steps {
        script {
          gitCheckout(
            branch: "main",
            url: "https://github.com/mo7medsalah7/java-maven-jenkins-k8s"
          )
        }
      }
    }


    // Maven Test
    stage('Maven Test') {
      script {

      }
    }
  }
}